name: CI/CD Pipeline with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    tests:
      name: Run tests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.2'
            extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
            coverage: none

        - name: Run composer install
          run: composer install -n --prefer-dist

        - name: Prepare Laravel Application
          run: |
            cp .env.ci .env
            php artisan key:generate

        - name: Run tests
          run: php artisan test

    deploy:
      runs-on: ubuntu-latest
      needs: tests
      if: github.ref == 'refs/heads/main'

      steps:
        # Step 1: Checkout code
        - name: Checkout Code
          uses: actions/checkout@v3

        # Step 2: SSH and Deploy with Docker Compose
        - name: Deploy to Server
          uses: appleboy/ssh-action@v0.1.5
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              cd main/peemco-coop
              git pull origin main
              docker-compose pull
              docker-compose up -d
