name: CI/CD Pipeline with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: TEst env
        run: |
          echo 'Test env ${{ vars.DB_DATABASE }}'
      - name: TEst secrets
        run: |
          echo 'Test env ${{ secrets.SSH_HOST }}'
    

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: SSH and Deploy with Docker Compose
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd main/peemco-coop
            git pull origin main
            docker-compose pull
            docker-compose up -d
